### ISSUE TITLE
Redactar documentación SPRINT 1

### ISSUE THREAD

**Issue by FreddyPinto** [Insights-Labs-Consultant-Agency/yelp-google-maps-reviews-and-recommendations#25]

**Comment by FreddyPinto** [comment]
Falta documentar el alcance temporal y actualizar documentación KPIs.

**Comment by cjpizarroz** [comment]
El proyecto se estructuro en tres Sprint, en un período de tres semanas totales, comenzando el 2 enero de 2024. Durante este tiempo, se realizaron análisis de los datos de Google Maps y Yelp. Se llevaron a cabo análisis georreferenciales para rastrear la popularidad y ubicación de las franquicias del cliente.
Los Sprint se distribuyeron de la siguiente manera:

_**📜 Sprint #1: Puesta en marcha del proyecto y Trabajo con Datos (Semana 1)**_

- **Entendimiento de la Situación Actual:** Análisis de la temática y los datos disponibles.
- **Objetivos:** Definición de objetivos concretos y KPIs asociados.
- **Alcance:** Delimitación del trabajo y definición de tareas fuera de alcance.
- **Repositorio Github:** Creación del repositorio colaborativo en Github.
- **Solución Propuesta:** Detallar tareas, productos y metodologías a utilizar.
- **Análisis Preliminar de Calidad de Datos:** Metadatos y análisis detallado sobre los datos disponibles.
- **Hitos y Entregables:** 3 KPIs, Documentación de alcance, EDA de los datos, Implementación del stack tecnológico, Metodología de trabajo, Diseño detallado, Equipo de trabajo - Roles y responsabilidades, Cronograma - Gantt, Análisis preliminar de calidad de datos.

_**👨‍💻 Sprint #2: Data Engineering (Semana 2)**_

- **ETL y Modelado de Datos:**  Montaje de infraestructura y desarrollo de pipelines ETL.
- **Modelo Entidad-Relación o No-Relacional:** Diseño detallado del modelo o justificación de modelo no relacional.
- **Análisis Exhaustivo en Muestra Representativa de Datos:** Identificación de valores atípicos, distribuciones y correlaciones.
- **Diseño de Dashboard (Prueba de Concepto) o Producto de ML (MVP):** Versión simplificada del dashboard o producto de ML con datos de muestra.
- **Hitos y Entregables:** ETL completo, Estructura de datos implementada, Pipeline ETL automatizado, Diseño del Modelo ER, Pipelines para alimentar el DW, Data Warehouse, Validación de datos, Documentación detallada.

_**📈 Sprint #3: Data Analytics + ML (Semana 3)**_

- **Desarrollo de Dashboard Interactivo y Análisis de Datos:** Creación de un dashboard interactivo y análisis de datos.
- **Implementación de Modelos de ML (si aplica):** Producto/s de ML, Modelo/s de ML en producción.
- **Diseño de Reportes/Dashboards y KPIs:** Finalización del dashboard, KPIs e informe de análisis.
- **Entregables Finales:** Dashboard final, Producto/s de ML, Documentación y reporte final.

**Comment by cjpizarroz** [comment]
KPIs
_**KPI 1 Satisfaccion al cliente** 
Nos permite evaluar directamente la percepción general de los clientes sobre nuestros servicios.  
Metrica: cantidad de reseñas positivas que recibe el cliente. 
Objetivo: aumentar un 10% las mismas en periodo trimestrales.

-**KPI 2 Cantidad de Reseñas por Sucursal**
Nos permite  comprender cómo cada sucursal está siendo percibida por los clientes y a identificar áreas de mejora a nivel local. 
Métrica: Cantidad de interacciones en las sucursales. Cantidad total de reseñas por sucursales/cantidad total de reseñas.
Objetivo: incrementar  un 5% las reseñas positivas mensualmente.

-**KPI 3 Satisfacción del Cliente respecto al Servicio**
Nos permite comprender en detalle los aspectos específicos de nuestros servicios, que impactan en la experiencia del cliente.
Metrica: Cantidad de comentarios negativos o positivos respecto al servicio sobre cantidad de comentarios totales.
Objetivo: aumentar un 5% los comentarios positivos y disminuir 5% la cantidad de comentarios negativos mensualmente.

_**KPI 4 Oferta/Demanda de comida saludable**
Nos permite tomar decisiones estratégicas, sobre la expansión de nuestra oferta de comida vegetaría/vegana en áreas con alta demanda relativa.
Metrica:  Cantidad de restaurantes de comida saludable/cantidad de reseñas de comida saludable por estado.
Objetivo: identificar el top 3 de ciudades potenciales por estado basados en esta métrica.
